### PR TITLE
Better camera movement and adjustable speeds (using UIExpansionKit as optional dependency)

### PR DESCRIPTION
**Pull request by Miner28**
Camera now actually moves to where its looking (not height, just **x** and **z**)  Changed few controls to arrow keys = movement on **x** and **z** axis and pageUp and pageDown on **y** axis numpad controls are also better now. 

Please feel free to rework it or do whatever with it.. I am newbie in C# and this is literally the first thing i made in C# soo its messy as hell..

### CODE REVIEW

**Comment by nitrog0d** [comment]
Thank you for the PR! I'll check it tomorrow when I have free time!

**Comment by ItsMeZeppelin** [comment]
Would recommend leaving the keybinds as how it was before or make it so that you can edit it in either modprefs or UIExpansionKit
[I tried it out earlier and it felt really good to set your own camera movement speed]

**Comment by nitrog0d** [comment]
That's mainly what was concerning me, the change of buttons, well anyway I'll see what I can do

**Comment by Miner28** [comment]
The change of buttons in my opinion is logical because why arrow up would bring the camera up and not forward. And even more so with the new way how camera movement works. Build it and try it yourself how it is now and if it feels better or worse.

**Comment by nitrog0d** [comment]
I know you closed this PR, but can I reopen it and use it?

**Comment by Miner28** [comment]
Yes I know I closed it because you were not doing anything soo I thought you just decided to not do anything. If you want you can use it yes.

**Comment by Miner28** [comment]
Yes you can I closed it because there was no response and it seemed like no updates were going to happen anymore.

**Comment by Miner28** [comment]
I can fix merge issues when I get home if needed

**Comment by nitrog0d** [comment]
If you can, please, thank you

**Comment by Miner28** [comment]
This should be working.. If i ever get bored i will open another PR with the fixes..

**Comment by nitrog0d** [comment]
Thank you, will release tomorrow

**Comment by nitrog0d** [comment]
Of course bad stuff happen when I'm supposed to do this... Sorry again, I'll try to get it done today

**Pull request merged**
